version: "3"
services:
  app:
    build: .
    ports:
      - "${DOCKERPORT}:58123"
      - "${PORT}:${PORT}"
      - "${PORThttps}:${PORThttps}"
    volumes:
      - "${privkey}:${privkey}"
      - "${cert}:${cert}"
      - "${chain}:${chain}"
      
    restart: always